#+TITLE: nncp-tools

Here you can find tools and documentation for [[https://nncp.mirrors.quux.org/][NNCP]].

* Included Documentation

- [[file:docs/quux-relay.org][Using the quux.org public NNCP relay]]
- [[file:docs/usenet.org][Using NNCP for Usenet]], including how to obtain a full Usenet feed from quux over NNCP [not yet done]
- [[file:docs/sdf.org][Using NNCP at the SDF Public Access UNIX system]] [not yet ready]
- [[file:docs/nncp-sudo.org][Using NNCP with sudo]]
- [[file:docs/tunneling.org][Tunneling NNCP over other transports]]

* Copyright

These files are Copyright (c) 2021 John Goerzen.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
