#!/usr/bin/env bash

usage () {
    cat <<EOF
Usage: cron-maint spooldir [xferdir]

Where:

spooldir is the path to the NNCP spool directory

xferdir is the path to the nncp-xfer exchange directory

Set NNCPCFG if needed.
EOF
    exit 10
}

set -euo pipefail

SPOOLDIR="$1"
XFERDIR="${2:-}"

if [ ! -d "$SPOOLDIR" ]; then
    usage
fi

find "$SPOOLDIR" -regex '.*/rx/.*' -a -type f -a -mtime +4 -delete
find "$SPOOLDIR" -regex '.*/tx/.*' -a -type f -a mtime +10 -delete
if [ -n "$XFERDIR" ]; then
    find "$XFERDIR" -type f -a mtime +10 -delete
fi
