#!/usr/bin/env bash

usage () {
    cat <<EOF
Usage: cron-maint xferdir spooldir

Where:

xferdir is the path to the nncp-xfer exchange directory

spooldir is the path to the NNCP spool directory

Set NNCPCFG if needed.
EOF
    exit 10
}

set -euo pipefail

XFERDIR="$1"
SPOOLDIR="$2"

if [ ! -d "$XFERDIR" ]; then
    usage
fi
if [ ! -d "$SPOOLDIR" ]; then
    usage
fi

find "$SPOOLDIR" -regex '.*/rx/.*' -a -type f -a -mtime +4 -delete
find "$SPOOLDIR" -regex '.*/tx/.*' -a -type f -a mtime +10 -delete
find "$XFERDIR" -type f -a mtime +10 -delete
