#!/usr/bin/env bash

# THIS SCRIPT IS UNTESTED.

usage () {
    cat <<EOF
Usage: cron-poll xferdir [pollnode]

Where:

xferdir is the path to the nncp-xfer exchange directory

pollhost is the optional node that we will poll for external traffic.

Set NNCPCFG if needed.
EOF
    exit 10
}

set -euo pipefail

XFERDIR="${1:-}"
POLLNODE="${2:-}"

if [ ! -d "$XFERDIR" ]; then
    usage
fi

nncp-toss -seen
nncp-xfer "$XFERDIR"
nncp-toss -seen
if [ -n "$POLLNODE" ]; then
    nncp-call -autotoss "$POLLNODE"
fi
nncp-toss -seen
nncp-xfer "$XFERDIR"
nncp-toss -seen
