#!/usr/bin/env bash

# This script is designed to be run by nncp-exec, accepting a tarball nodelist
# on stdin and updating it as appropriate.
#

set -euo pipefail

TMPDIR="`mktemp -d`"
trap 'ECODE=$?; rm -r "$TMPDIR"; exit $ECODE' EXIT INT TERM

cd "$TMPDIR"

tar -zxf -

cd nodelist/for-use

cat >> quux <<EOF
calls: [
  {
   cron: "0 * * * * * *"
   when-tx-exists: true
  }
]

exec: {
  nodelistupdate: ["/meta/j/jgoerzen/nncp-tools/scripts/receive-nodelist-sdfrelay"]
}
EOF
# Remove the ability of any but our SDF peers and quux to communicate here.

for FILE in *; do
    if [ "$FILE" = "quux" ] || echo "$FILE" | grep -q '\.sdf\.org$'; then
        # don't mess with this
        true
    else
        sed -i 's/noisepub:.*//' "$FILE"
    fi
done

~/nncp-tools/scripts/update-nodelist relay.sdf.org "`pwd`" ~/nncp/etc/nncp.hjson.pre ~/nncp/etc/nncp.hjson.post '\.sdf\.org$' > ~/nncp/etc/nncp.hjson
