#!/usr/bin/env bash

# This script is designed to be run by nncp-exec, accepting a tarball nodelist
# on stdin and updating it as appropriate.
#
# Pass this node's name as $1

set -euo pipefail

NODENAME="$1"

TMPDIR="`mktemp -d`"
trap 'ECODE=$?; rm -r "$TMPDIR"; exit $ECODE' EXIT INT TERM

cd "$TMPDIR"

tar -zxf -

cd nodelist/for-use

# Everything outbound from here goes via the SDF relay.

~/nncp-tools/scripts/update-nodelist "$NODENAME" "`pwd`" ~/nncp/etc/nncp.hjson.pre ~/nncp/etc/nncp.hjson.post '.*' '"relay.sdf.org"' > ~/nncp/etc/nncp.hjson
