#!/usr/bin/env bash

set -euo pipefail

if pgrep -u `id -nu` nncp-daemon > /dev/null && \
    pgrep -u `id -nu` nncp-caller > /dev/null && \
    pgrep -u `id -nu` nncp-toss > /dev/null; then
    # everything is up
    true
else
    ~/nncp-tools/scripts/restart-sdfrelay
fi
