#+TITLE: Obtaining Usenet via NNCP

* Introduction to NNCP
According to the [[https://nncp.mirrors.quux.org/][NNCP documentation]], NNCP is intended to help build up small size ad-hoc friend-to-friend (F2F) statically routed darknet delay-tolerant networks for fire-and-forget secure reliable files, file requests, Internet mail and commands transmission. All packets are integrity checked, end-to-end encrypted, explicitly authenticated by known participants public keys. Onion encryption is applied to relayed packets. Each node acts both as a client and server, can use push and poll behaviour model. Also there is multicasting area support.  NNCP can operate over a lot of transports: Internet, USB sticks, tapes, CD-ROMs, and [[file:tunneling.org][some more]] such as ssh, socat, Dropbox, and so forth.

The NNCP homepage is <http://www.nncpgo.org>.  A mirror using TLS and Let's Encrypt is at <https://nncp.mirrors.quux.org>.

* Introduction to Usenet

[[https://en.wikipedia.org/wiki/Usenet][Usenet]] is sometimes said to be the world's oldest social network.  Since 1980, Usenet has been a massive, global discussion system.  Participants can read and post messages (called articles) in discussion forums (called newsgroups).  Unlike web forums, Usenet newgroups are available from thousands of independently-operated servers worldwide (instead of just one particular site).  You can also use the client of your choice to access them.

Although it is transferred almost exclusively over the Internet using [[https://en.wikipedia.org/wiki/Network_News_Transfer_Protocol][NNTP]] these days, in the early days, Usenet data was exchanged using [[https://en.wikipedia.org/wiki/UUCP][UUCP]], the ancestor technology of NNCP (much as rsh/telnet are ancestors to ssh).

** Suitable for both large & small scales

A Usenet server that is a full participant in the global system can be quite massive.  There are "binaries" newsgroups, in which people post large image or video files.  These are mostly the realm of commercial pay-for servers, and we aren't concerned with them here.  We are talking about discussion groups.  While the overall load for those is <100MB per day, operating a full-fledged Usenet server on the Internet can be heavy in terms of administrative resources, needing to have a 24/7 connection with a static IP that accepts inbound connections, maintaining spam filters, etc.  An NNCP feed is ideal for people that wish to run a smaller server -- perhaps even on a Raspberry Pi or some other very cheap system -- that doesn't have a public IP and may not be permanently connected to the Internet.

Since the tools that operate Usenet come from an era in which even a Raspberry Pi would have been an unimaginablely high level of computing power, the resource requirements for a small site are quite minimal.  You could, for instance, operate a family bulletin board, a discussion group among friends, or even something more unique using various Usenet gateways: for instance, a RSS-to-Usenet interface, etc.  This could all operate on a Raspberry Pi, and nodes could exchange articles via NNCP.  In a closed system like this, NNCP's multicast areas would be perfect, requiring minimal configuration on the Usenet side with maximum flexibility for you.

* Intent of this document

This document is primarily intended to let you operate as a leaf node for news.quux.org, the Usenet transit server operated principally by [[https://www.complete.org/JohnGoerzen][John Goerzen]].  news.quux.org has several peers with which it exchanges Usenet articles, and is able to offer you a full (basically every non-binary newsgroup) or partial (the newsgroups you select) feed.

Secondary intents are to:

- Demonstrate how to integrate INN with NNCP
- Explain how you might operate a standalone (not connected with the global Usenet) INN network using NNCP.  This scenario is actually simpler than participating in the public Usenet, so much of what is said here may not apply to you.

* What can you do with a NNCP Usenet feed from quux?

Here are some examples:

- Set up a personal news server for your own use, which you can use to read and post articles, search through, etc.
- Set up a news server for yourself, friends, and family
- Receive content from quux and further restribute it to your friends (establishing your own peers is up to you, and doesn't require any involvement from quux)
  - You can also do the reverse; feed posts your friends send you via NNCP to quux and thus to the global Usenet.

* Prerequisites

Before continuing, you must already:

- Be familiar with and operating [[https://nncp.mirrors.quux.org/][NNCP]]
- Have a working understanding of Usenet.
- Be comfortable with the Linux/BSD/Unix command line.

If you are not already familiar with Usenet, it would probably be a good idea to dive in!

Start with a newsreader program.  [[https://www.thunderbird.net/en-US/][Mozilla Thunderbird]] or [[http://pan.rebelbase.com/][PAN]] may be good places to start.  (For Thunderbird, add a new "other" account, for Usenet/newsgroup access).  You can get a free Usenet account from [[http://news.aioe.org/][AIOE]] or [[https://www.eternal-september.org/][Eternal September]] to use with it.  Don't skip this step!

** Requirements for an NNCP feed from news.quux.org

Because news.quux.org is capable of feeding your Usenet posts to thousands of Usenet servers across the globe, some additional requirements apply:

- Your NNCP data will be exchanged using the [[file:quux-relay.org][quux.org public NNCP relay]].  So, you will need to establish yourself as an NNCP peer with it according to its [[file:quux-relay.org][documentation]].  (This is a quick and simple process.)

- If you discontinue using the quux NNCP gateway -- and that's fine -- you need to let me know, so we don't build up an endless set of articles for a system that will never talk to us again.

- You must not operate an open or public relay.  Generally, that means "don't expose any ports on your Usenet server to the Internet."
  - If you must expose the NNTP port to the Internet - which is discouraged in this situation - it must require authentication and you must not hand out accounts to the public.  As with an email service, operating a Usenet service that is open to the world would be ripe for abuse.  Those at AIOE and Eternal September have years of experience preventing that, and running a public relay from quux over NNCP is just going to be more pain than any of us have time to deal with.

- news.quux.org is a well-connected transit system, and as such will send you articles from the public Internet.  While measures are taken to filter at quux, you must understand and agree that, like much of the public Internet, Usenet has no central authority and you may encounter content you find objectionable.  Content policing is up to each individual server operator in Usenet, which will now include YOU.  Be familiar with what's out there before, for instance, you offer it to children.

- Similarly, it is your duty to not spread objectionable content to the Internet via quux.  Examples of objectionable content include that which is illegal, spam, abusive or exploitative, "doxxing", harassing, impersonating others with fake headers or the like, threatening or causing harm (including by spreading health misinformation), and so forth.  While there are corners of the global Usenet that have ugly behavior, and news.quux.org being fundamentally a dumb machine that just copies data from point A to B means that you may encounter this, there is a also an effort to make more parts of the Internet a positive environment, and quux.org is part of that effort.  https://floss.social/terms is an example of the kind of conduct we would like to see from articles you feed to us.  *We want to be part of the solution, not part of the problem.*
  + If you provide access to others in any way, whether by letting them access your server or by becoming NNCP peers with them, you need to make sure they understand their responsibilities on what gets injected to the globe via you, and be prepared to enforce standards of behavior.  You may, for instance, need to cut them off if they engage in objectionable behavior via your system.  Keep this in mind.
  + If persistent abuse occurs from your site which you are unable or unwilling to correct, or particularly egregious abuse occurs, your feed may be canceled.
  + You must have up-to-date contact information on file with me at quux, so that you can be reached in the event complaints are received about your site at quux.  The idea is to resolve things collaboratively so that feed interruption need not occur -- but moreover, to prevent issues from occurring in the first place.
  + Also this service is all-volunteer without guarantee of correct operation or the continuing operation of any feed.

You should also be aware, in case you are planning to take your solar-powered Raspberry Pi with INN and NNCP with you on a 3-week hike across the remotest parts of Canada, writing articles to pass the time and posting them when you reach civilization, that most Usenet sites reject articles that reach them if they are older than a certain number of days.  For most, that number is 10, but it may be as little as 1 or 2 on some.  So if you are feeding data TO the Internet via quux, keep that in mind.  For data coming to YOU from quux, you can set the limit whatever you like (but the quux public relay may also auto-reap packets of advanced age that are bound to you).  So basically if you want to use this, checking in daily will probably work; weekly will probably usually work, and monthly will not.

* The Big Picture: How it Works

There are various Usenet servers; for this, we will use INN 2.6.

INN still has UUCP support.  NNCP presents an interface that is almost identical to UUCP, so we will be generally configuring INN as if it's exchanging articles by UUCP.

Here's how INN generally works in a UUCP/NNCP scenario:

- Incoming articles from news.quux.org are fed from the tosser (nncp-toss / uuxqt) to a program called rnews, which is part of the INN distribution and injects them into the local server.
- For articles you feed to quux, INN maintains a small file with information about them -- basically a "storage token" to find them on disk and a size.  From cron, send-uucp (also part of INN) goes through those INN files and generates batches of articles to be sent to quux's rnews via NNCP, using nncp-exec (our version of UUCP's uux).

This is basically using a tried-and-true method that has worked with INN's UUCP support for decades.  All we are doing is substituting NNCP for the UUCP layer.  We are not using NNCP's multicast areas for this; see the conversation below about this.

* Planning

Before getting started, you need to think about a few things.

** Your Usenet hostname

The Usenet hostname you set is a vital part of preventing routing loops and duplicate messages on Usenet.  It does not have to be a valid Internet hostname (though it often is).  It does have to be globally unique, and it also ought to serve to identify your system.

If you already own a DNS domain, you could use something under that.  For instance, if you have registered example.com, you might consider news.nncp.example.com.  It is fine if =news.nncp.example.com= doesn't resolve in DNS; it just needs to not be used for something else.

If you don't own a DNS domain, then you may have to make something up, perhaps ending in =.nncp=.  For instance, =news.smith.newark.nj.us.nncp= or something.  Visit with me about this if you like.  The key is that there must be no chance of an accidental use of the same name by some other system anywhere on the planet.

** What newsgroups?

You can opt to carry a "full feed" from quux - that is, basically everything that transits quux will be sent to you.  The concept of "everything" is a little different at each site due to things like spam filters.

Or, you can opt to carry a handful of specific newsgroups -- say, =comp.mail.uucp=.  Or an entire hierarchy; say, =comp.*= or =comp.mail.*=.  These can be changed later, but do require manual config file editing on my part, so be aware that a change doesn't happen instantly.

New newsgroups are often created (or added to quux because a new feed is added which carries them).

You can get a sense of what newsgroups are out there by looking at the ISC's files at ftp://ftp.isc.org/pub/usenet/CONFIG .  The file =active= in that directory contains a list of every newsgroup believed to be active at ISC.  The file =newsgroups= contains descriptions for many, but not all, newsgroups.  Be aware that the actual set of carried newsgroups varies from site to site, particularly for =alt.*= which lacks a formal process for authorizing new groups.

Some newsgroups are /moderated/; that is, you can't post directly to them.  When you attempt to post to a moderated group, INN will actually submit your post via email to the moderator, rather than post it to Usenet.  Therefore, if you intend to post to a moderated group, you will require working email service on your Usenet server.  Moderated newsgroups today are often quite low-traffic and rarely posted to by the public.  You can identify a moderated group because, in the active file from ISC, the line ends with =m= instead of =y=.

* Setting up NNCP

OK, let's begin!  This is the easy part.  First, you need to have done the setup for the [[file:quux-relay.org][quux public relay]], which will have included adding the quux definition to your nncp.hjson.  Then, you need to note the quux news server in your nncp.hjson's neigh section:

#+begin_example
    news.quux.org: {
      id: 6QVFU7QIHQNI6TWNRK7OAJUUBDZT262XX3I5YHGZOGLTVYOQM47Q
      exchpub: DBHZYJFEXNGJ5UFC6TZVYRAAAKKKVLT3DAAXCQXZZYERXPLLEQIQ
      signpub: OKFURSS5YFXUEEPYCAEGPBIPZDHDBISNJA47LHGMVECH6KC5PEWA
      noisepub: ZXEYBPZN5WAI4674NBF5ZRX6ZG7YEILVMRDGQT3NWHA7Q5ZMXQXQ
      via: ["quux"]
      incoming: "/tmp"  # or more appropriate path; only if you intend to freq active from news.quux.org
      exec: {
        rnews: ["/usr/bin/rnews", "-h", "news.quux.org"]
      }
    }
#+end_example

Here you have set up NNCP so that rnews can be executed to process incoming packets from quux.  As a further exercise for added security, you should wrap it with a script that prevents any further arguments to rnews (since NNCP otherwise permits that), but this simple example gets you started.

The last remaining part is to allow the =news= user to queue up packets using =nncp-exec=.  There are two ways you can do that:
- [[https://nncp.mirrors.quux.org/Administration.html#Shared-spool][NNCP's shared spool]] configuration.  You would need to add the =news= user to the =nncp= group for this one.
- Or, you can [[file:nncp-sudo.org][configure sudo for NNCP]] to allow the =news= user to effectively run =sudo -u nncp nncp-exec=.

What you do is up to you.  Allowing the news user permissions to NNCP does mean that it could access the NNCP private keys if there was a security breach in the INN process or something, but whether you care about that possibility is up to you.

It is not necessary to run =rnews= as the news user, since it feeds to INN by connecting to localhost:119.

That's it.  You're done configuring NNCP!

* Getting started with INN

* Copyright

These files are Copyright (c) 2021 John Goerzen.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
